[tool.poetry]
name = "idealfunctions"
version = "0.1.0"
description = ""
authors = ["Dai Hai Le <DaiHai.Le@neurotransdata.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
numpy = "==2.3.4"
pandas = "==2.3.3"
sqlalchemy = "==2.0.44"
bokeh = "^3.8.1"
pytest = "==9.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
